// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package post

import (
	"context"
	"fmt"
)

type CreatePostReq struct {
	UserID   int64  `thrift:"userID,1" frugal:"1,default,i64" json:"userID"`
	PostName string `thrift:"postName,2" frugal:"2,default,string" json:"postName"`
	Content  string `thrift:"content,3" frugal:"3,default,string" json:"content"`
}

func NewCreatePostReq() *CreatePostReq {
	return &CreatePostReq{}
}

func (p *CreatePostReq) InitDefault() {
}

func (p *CreatePostReq) GetUserID() (v int64) {
	return p.UserID
}

func (p *CreatePostReq) GetPostName() (v string) {
	return p.PostName
}

func (p *CreatePostReq) GetContent() (v string) {
	return p.Content
}
func (p *CreatePostReq) SetUserID(val int64) {
	p.UserID = val
}
func (p *CreatePostReq) SetPostName(val string) {
	p.PostName = val
}
func (p *CreatePostReq) SetContent(val string) {
	p.Content = val
}

func (p *CreatePostReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreatePostReq(%+v)", *p)
}

var fieldIDToName_CreatePostReq = map[int16]string{
	1: "userID",
	2: "postName",
	3: "content",
}

type CreatePostResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	PostID  int64  `thrift:"postID,2" frugal:"2,default,i64" json:"postID"`
	Msg     string `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewCreatePostResp() *CreatePostResp {
	return &CreatePostResp{}
}

func (p *CreatePostResp) InitDefault() {
}

func (p *CreatePostResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *CreatePostResp) GetPostID() (v int64) {
	return p.PostID
}

func (p *CreatePostResp) GetMsg() (v string) {
	return p.Msg
}
func (p *CreatePostResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *CreatePostResp) SetPostID(val int64) {
	p.PostID = val
}
func (p *CreatePostResp) SetMsg(val string) {
	p.Msg = val
}

func (p *CreatePostResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreatePostResp(%+v)", *p)
}

var fieldIDToName_CreatePostResp = map[int16]string{
	1: "success",
	2: "postID",
	3: "msg",
}

type DeletePostReq struct {
	UserID int64 `thrift:"userID,1" frugal:"1,default,i64" json:"userID"`
	PostID int64 `thrift:"postID,2" frugal:"2,default,i64" json:"postID"`
}

func NewDeletePostReq() *DeletePostReq {
	return &DeletePostReq{}
}

func (p *DeletePostReq) InitDefault() {
}

func (p *DeletePostReq) GetUserID() (v int64) {
	return p.UserID
}

func (p *DeletePostReq) GetPostID() (v int64) {
	return p.PostID
}
func (p *DeletePostReq) SetUserID(val int64) {
	p.UserID = val
}
func (p *DeletePostReq) SetPostID(val int64) {
	p.PostID = val
}

func (p *DeletePostReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeletePostReq(%+v)", *p)
}

var fieldIDToName_DeletePostReq = map[int16]string{
	1: "userID",
	2: "postID",
}

type DeletePostResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewDeletePostResp() *DeletePostResp {
	return &DeletePostResp{}
}

func (p *DeletePostResp) InitDefault() {
}

func (p *DeletePostResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *DeletePostResp) GetMsg() (v string) {
	return p.Msg
}
func (p *DeletePostResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *DeletePostResp) SetMsg(val string) {
	p.Msg = val
}

func (p *DeletePostResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeletePostResp(%+v)", *p)
}

var fieldIDToName_DeletePostResp = map[int16]string{
	1: "success",
	2: "msg",
}

type PostService interface {
	CreatePost(ctx context.Context, req *CreatePostReq) (r *CreatePostResp, err error)

	DeletePost(ctx context.Context, req *DeletePostReq) (r *DeletePostResp, err error)
}

type PostServiceCreatePostArgs struct {
	Req *CreatePostReq `thrift:"req,1" frugal:"1,default,CreatePostReq" json:"req"`
}

func NewPostServiceCreatePostArgs() *PostServiceCreatePostArgs {
	return &PostServiceCreatePostArgs{}
}

func (p *PostServiceCreatePostArgs) InitDefault() {
}

var PostServiceCreatePostArgs_Req_DEFAULT *CreatePostReq

func (p *PostServiceCreatePostArgs) GetReq() (v *CreatePostReq) {
	if !p.IsSetReq() {
		return PostServiceCreatePostArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PostServiceCreatePostArgs) SetReq(val *CreatePostReq) {
	p.Req = val
}

func (p *PostServiceCreatePostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PostServiceCreatePostArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceCreatePostArgs(%+v)", *p)
}

var fieldIDToName_PostServiceCreatePostArgs = map[int16]string{
	1: "req",
}

type PostServiceCreatePostResult struct {
	Success *CreatePostResp `thrift:"success,0,optional" frugal:"0,optional,CreatePostResp" json:"success,omitempty"`
}

func NewPostServiceCreatePostResult() *PostServiceCreatePostResult {
	return &PostServiceCreatePostResult{}
}

func (p *PostServiceCreatePostResult) InitDefault() {
}

var PostServiceCreatePostResult_Success_DEFAULT *CreatePostResp

func (p *PostServiceCreatePostResult) GetSuccess() (v *CreatePostResp) {
	if !p.IsSetSuccess() {
		return PostServiceCreatePostResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PostServiceCreatePostResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreatePostResp)
}

func (p *PostServiceCreatePostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PostServiceCreatePostResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceCreatePostResult(%+v)", *p)
}

var fieldIDToName_PostServiceCreatePostResult = map[int16]string{
	0: "success",
}

type PostServiceDeletePostArgs struct {
	Req *DeletePostReq `thrift:"req,1" frugal:"1,default,DeletePostReq" json:"req"`
}

func NewPostServiceDeletePostArgs() *PostServiceDeletePostArgs {
	return &PostServiceDeletePostArgs{}
}

func (p *PostServiceDeletePostArgs) InitDefault() {
}

var PostServiceDeletePostArgs_Req_DEFAULT *DeletePostReq

func (p *PostServiceDeletePostArgs) GetReq() (v *DeletePostReq) {
	if !p.IsSetReq() {
		return PostServiceDeletePostArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PostServiceDeletePostArgs) SetReq(val *DeletePostReq) {
	p.Req = val
}

func (p *PostServiceDeletePostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PostServiceDeletePostArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceDeletePostArgs(%+v)", *p)
}

var fieldIDToName_PostServiceDeletePostArgs = map[int16]string{
	1: "req",
}

type PostServiceDeletePostResult struct {
	Success *DeletePostResp `thrift:"success,0,optional" frugal:"0,optional,DeletePostResp" json:"success,omitempty"`
}

func NewPostServiceDeletePostResult() *PostServiceDeletePostResult {
	return &PostServiceDeletePostResult{}
}

func (p *PostServiceDeletePostResult) InitDefault() {
}

var PostServiceDeletePostResult_Success_DEFAULT *DeletePostResp

func (p *PostServiceDeletePostResult) GetSuccess() (v *DeletePostResp) {
	if !p.IsSetSuccess() {
		return PostServiceDeletePostResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PostServiceDeletePostResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeletePostResp)
}

func (p *PostServiceDeletePostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PostServiceDeletePostResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PostServiceDeletePostResult(%+v)", *p)
}

var fieldIDToName_PostServiceDeletePostResult = map[int16]string{
	0: "success",
}
