input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => "\[%{DATA:extracted_service}\]\s*(?<json_message>.+)" }
  }

  json {
    source => "json_message"
    target => "parsed"
  }

  mutate {
    add_field => {
      "service" => "%{[parsed][service]}"
      "level" => "%{[parsed][level]}"
      "error_message" => "%{[parsed][error]}"
      "log_message" => "%{[parsed][message]}"
      "caller" => "%{[parsed][caller]}"
    }

    replace => { "service" => "%{extracted_service}" }

    remove_field => ["json_message", "message", "parsed"]
  }

  date {
    match => ["[parsed][timestamp]", "yyyy-MM-dd HH:mm:ss", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "services-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}