// Code generated by Kitex v0.16.1. DO NOT EDIT.

package postservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	post "microservicesDemo/L7-ELK/kitex_gen/post"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreatePost(ctx context.Context, req *post.CreatePostReq, callOptions ...callopt.Option) (r *post.CreatePostResp, err error)
	DeletePost(ctx context.Context, req *post.DeletePostReq, callOptions ...callopt.Option) (r *post.DeletePostResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPostServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPostServiceClient struct {
	*kClient
}

func (p *kPostServiceClient) CreatePost(ctx context.Context, req *post.CreatePostReq, callOptions ...callopt.Option) (r *post.CreatePostResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePost(ctx, req)
}

func (p *kPostServiceClient) DeletePost(ctx context.Context, req *post.DeletePostReq, callOptions ...callopt.Option) (r *post.DeletePostResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePost(ctx, req)
}
