// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type RegisterReq struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Email    string `thrift:"email,3" frugal:"3,default,string" json:"email"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterReq) GetEmail() (v string) {
	return p.Email
}
func (p *RegisterReq) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterReq) SetEmail(val string) {
	p.Email = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "username",
	2: "password",
	3: "email",
}

type RegisterResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	UserID  int64  `thrift:"userID,2" frugal:"2,default,i64" json:"userID"`
	Msg     string `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

func (p *RegisterResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *RegisterResp) GetUserID() (v int64) {
	return p.UserID
}

func (p *RegisterResp) GetMsg() (v string) {
	return p.Msg
}
func (p *RegisterResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *RegisterResp) SetUserID(val int64) {
	p.UserID = val
}
func (p *RegisterResp) SetMsg(val string) {
	p.Msg = val
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "success",
	2: "userID",
	3: "msg",
}

type LoginByUsernameReq struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginByUsernameReq() *LoginByUsernameReq {
	return &LoginByUsernameReq{}
}

func (p *LoginByUsernameReq) InitDefault() {
}

func (p *LoginByUsernameReq) GetUsername() (v string) {
	return p.Username
}

func (p *LoginByUsernameReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginByUsernameReq) SetUsername(val string) {
	p.Username = val
}
func (p *LoginByUsernameReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginByUsernameReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginByUsernameReq(%+v)", *p)
}

var fieldIDToName_LoginByUsernameReq = map[int16]string{
	1: "username",
	2: "password",
}

type LoginByUsernameResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Token   string `thrift:"token,2" frugal:"2,default,string" json:"token"`
	Msg     string `thrift:"msg,3" frugal:"3,default,string" json:"msg"`
}

func NewLoginByUsernameResp() *LoginByUsernameResp {
	return &LoginByUsernameResp{}
}

func (p *LoginByUsernameResp) InitDefault() {
}

func (p *LoginByUsernameResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *LoginByUsernameResp) GetToken() (v string) {
	return p.Token
}

func (p *LoginByUsernameResp) GetMsg() (v string) {
	return p.Msg
}
func (p *LoginByUsernameResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *LoginByUsernameResp) SetToken(val string) {
	p.Token = val
}
func (p *LoginByUsernameResp) SetMsg(val string) {
	p.Msg = val
}

func (p *LoginByUsernameResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginByUsernameResp(%+v)", *p)
}

var fieldIDToName_LoginByUsernameResp = map[int16]string{
	1: "success",
	2: "token",
	3: "msg",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginByUsernameReq) (r *LoginByUsernameResp, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginByUsernameReq `thrift:"req,1" frugal:"1,default,LoginByUsernameReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginByUsernameReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginByUsernameReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginByUsernameReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginByUsernameResp `thrift:"success,0,optional" frugal:"0,optional,LoginByUsernameResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginByUsernameResp

func (p *UserServiceLoginResult) GetSuccess() (v *LoginByUsernameResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginByUsernameResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}
