// Code generated by Kitex v0.16.1. DO NOT EDIT.

package postservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	post "microservicesDemo/L5-kafka/kitex_gen/post"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreatePost": kitex.NewMethodInfo(
		createPostHandler,
		newPostServiceCreatePostArgs,
		newPostServiceCreatePostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeletePost": kitex.NewMethodInfo(
		deletePostHandler,
		newPostServiceDeletePostArgs,
		newPostServiceDeletePostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	postServiceServiceInfo                = NewServiceInfo()
	postServiceServiceInfoForClient       = NewServiceInfoForClient()
	postServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return postServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return postServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return postServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PostService"
	handlerType := (*post.PostService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "post",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createPostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceCreatePostArgs)
	realResult := result.(*post.PostServiceCreatePostResult)
	success, err := handler.(post.PostService).CreatePost(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceCreatePostArgs() interface{} {
	return post.NewPostServiceCreatePostArgs()
}

func newPostServiceCreatePostResult() interface{} {
	return post.NewPostServiceCreatePostResult()
}

func deletePostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceDeletePostArgs)
	realResult := result.(*post.PostServiceDeletePostResult)
	success, err := handler.(post.PostService).DeletePost(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceDeletePostArgs() interface{} {
	return post.NewPostServiceDeletePostArgs()
}

func newPostServiceDeletePostResult() interface{} {
	return post.NewPostServiceDeletePostResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreatePost(ctx context.Context, req *post.CreatePostReq) (r *post.CreatePostResp, err error) {
	var _args post.PostServiceCreatePostArgs
	_args.Req = req
	var _result post.PostServiceCreatePostResult
	if err = p.c.Call(ctx, "CreatePost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeletePost(ctx context.Context, req *post.DeletePostReq) (r *post.DeletePostResp, err error) {
	var _args post.PostServiceDeletePostArgs
	_args.Req = req
	var _result post.PostServiceDeletePostResult
	if err = p.c.Call(ctx, "DeletePost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
