version: '3.8'

networks:
  otel-network:
    driver: bridge

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ../config/collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "8079:4317"
      - "8082:4318"
      - "8889:8889"
    networks:
      - otel-network
    restart: unless-stopped
    command: ["--config=/etc/otelcol-contrib/config.yaml"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../config/prometheus.yaml:/etc/prometheus/prometheus.yml # 确保为yml，Prometheus只会读取yml配置文件，又找了几个小时的bug
    ports:
      - "8084:9090"
    networks:
      - otel-network
    restart: unless-stopped
    depends_on:
      - otel-collector

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "8085:16686"
    networks:
      - otel-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - "8086:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - otel-network
    restart: unless-stopped
    depends_on:
      - prometheus
      - jaeger

volumes:
  grafana-data: